### PR TITLE
Implement AES-CTR mode.

### PR DESCRIPTION
**Pull request by Tronic**
Added `plusaes::crypt_ctr` function for CTR mode encryption and decryption.

Tested and confirmed working against Python.Cryptography AES-CTR mode.

### CODE REVIEW

**Comment by kkAyataka** [comment]
Thank you for your great job!

**Comment by Tronic** [comment]
What I really wanted was GCM mode but I didn't yet figure out how to do 128 bit Galois field multiplication, necessary for calculating the verification tag. That seems related to the mul and mul2 ops already used in AES itself.

**Comment by kkAyataka** [comment]
Sorry for my late reply.

I will merge this PR as Beta for now. But, I might change API in the future.

> GCM Mode

I will try to consider it, too.

**Comment by Tronic** [comment]
Feel free to merge, I am finished with CTR and have a separate branch for GCM with a partial implementation: https://github.com/Tronic/plusaes/tree/gcm

The biggest obstacle is missing gmul128. There is a plain-C implementation in that could perhaps be used with modifications:
https://bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/hash/ghash_ctmul64.c;h=a46f16fee977f6102abea7f7bcdf169a013c3e8e;hb=refs/heads/master

x86 CPUs also have an opcode for that but depending on things like that kind of defeat the purpose of a header-only library, i.e. being dead simple to use in a project.

Regarding API: I was also considering C++ containers/iterators instead of pointer + size, and throwing exceptions on errors. I would not go further than that because the modes differ to such a degree that a common API like `encrypt(data, key, MODE_CTR)` or different modes by OOP/inheritance cannot work very well (others have tried because OOP was cool in the 2000's).

**Comment by kkAyataka** [comment]
Thank you.

> C++ containers

This library use C-style signature in the API interface. I envision to build as dynamic link library.

I use this library with a thin C++ wrapper functions. C++ containers and exception are used.

> Common API

I think so too. The required arguments are different for each mode. So I think that the common API is difficult to use it and to understand the behavior.

**Pull request merged**
